const clothingItems = [
  {
    id: 1,
    name: "Classic White T-Shirt",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black", "Grey"],
    price: 1999,
    description: "A classic white t-shirt made from 100% organic cotton.",
    material: "100% Cotton",
    stock: 120,
    images: [
      "https://i.postimg.cc/6QQh9366/white-front.png",
      "https://i.postimg.cc/CKLVSjfZ/Screenshot-2024-07-27-101056.png",
    ],
  },
  {
    id: 2,
    name: "Slim Fit Jeans",
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Blue", "Black", "Grey"],
    price: 4999,
    description: "Stylish slim fit jeans with a modern look.",
    material: "98% Cotton, 2% Elastane",
    stock: 75,
    images: [
      "https://i.postimg.cc/bJZrNX22/Screenshot-2024-07-27-101301.png",
      "https://i.postimg.cc/yYQGcwJN/Screenshot-2024-07-27-101413.png",
    ],
  },
  {
    id: 3,
    name: "Floral Summer Dress",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Blue", "Yellow"],
    price: 3999,
    description: "A beautiful floral summer dress perfect for sunny days.",
    material: "100% Polyester",
    stock: 50,
    images: [
      "https://i.postimg.cc/Dfsj8ShB/Screenshot-2024-07-27-101544.png",
      "https://i.postimg.cc/Dfsj8ShB/Screenshot-2024-07-27-101544.png",
    ],
  },
  {
    id: 4,
    name: "Men's Leather Jacket",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Brown"],
    price: 12.99,
    description: "Premium quality leather jacket for men.",
    material: "100% Genuine Leather",
    stock: 30,
    images: [
      "https://i.postimg.cc/fT1r81sT/Screenshot-2024-07-27-101740.png",
      "https://i.postimg.cc/KjMHb5ry/Screenshot-2024-07-27-101750.png",
    ],
  },
  {
    id: 5,
    name: "Comfy Hoodie",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Grey", "Black", "Navy Blue"],
    price: 2999,
    description: "A cozy and comfortable hoodie made from soft fabric.",
    material: "60% Cotton, 40% Polyester",
    stock: 100,
    images: [
      "https://i.postimg.cc/5ymb11mJ/Screenshot-2024-07-27-101936.png",
      "https://i.postimg.cc/g2840JZ3/Screenshot-2024-07-27-101955.png",
    ],
  },

  {
    id: 6,
    name: "Casual Chinos",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Beige", "Navy Blue", "Olive"],
    price: 3499,
    description: "Comfortable and stylish chinos for casual wear.",
    material: "100% Cotton",
    stock: 80,
    images: [
      "https://i.postimg.cc/zvpwhbkc/Screenshot-2024-07-27-102155.png",
      "https://i.postimg.cc/nh97FwN5/Screenshot-2024-07-27-102213.png",
    ],
  },
  {
    id: 7,
    name: "Striped Polo Shirt",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red/White", "Blue/White", "Green/White"],
    price: 2499,
    description: "A stylish striped polo shirt made from breathable fabric.",
    material: "100% Cotton",
    stock: 90,
    images: [
      "https://i.postimg.cc/6TJKdq5C/Screenshot-2024-07-27-102320.png",
      "https://i.postimg.cc/htKjwZcT/Screenshot-2024-07-27-102330.png",
    ],
  },
  {
    id: 8,
    name: "Women's Cardigan",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Grey", "Black", "Pink"],
    price: 4499,
    description: "A soft and warm cardigan for women.",
    material: "80% Wool, 20% Acrylic",
    stock: 40,
    images: [
      "https://i.postimg.cc/15C2hfZB/Screenshot-2024-07-27-102458.png",
      "https://i.postimg.cc/ydHrXRF1/Screenshot-2024-07-27-102505.png",
    ],
  },
  {
    id: 9,
    name: "Plaid Button-Down Shirt",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red Plaid", "Blue Plaid", "Green Plaid"],
    price: 2999,
    description: "A classic plaid button-down shirt with a modern fit.",
    material: "100% Cotton",
    stock: 65,
    images: [
      "https://i.postimg.cc/d0YJ9z9W/plaid-shirt-1.png",
      "https://i.postimg.cc/8PrTbWm3/plaid-shirt-2.png",
    ],
  },
  {
    id: 10,
    name: "Denim Jacket",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Light Blue", "Dark Blue"],
    price: 5999,
    description: "Trendy denim jacket with a distressed finish.",
    material: "100% Denim",
    stock: 45,
    images: [
      "https://i.postimg.cc/d0J0Y6cz/denim-jacket-1.png",
      "https://i.postimg.cc/SR4cvMbg/denim-jacket-2.png",
    ],
  },
  {
    id: 11,
    name: "Belted Trench Coat",
    sizes: ["M", "L", "XL"],
    colors: ["Beige", "Navy Blue"],
    price: 7999,
    description: "Elegant belted trench coat for a sophisticated look.",
    material: "70% Polyester, 30% Cotton",
    stock: 30,
    images: [
      "https://i.postimg.cc/5yvjLw8r/trench-coat-1.png",
      "https://i.postimg.cc/9X5jtpZJ/trench-coat-2.png",
    ],
  },
  {
    id: 12,
    name: "Graphic Tee",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Charcoal"],
    price: 1499,
    description: "Comfortable graphic tee with a trendy design.",
    material: "100% Cotton",
    stock: 100,
    images: [
      "https://i.postimg.cc/bJHwCqv4/graphic-tee-1.png",
      "https://i.postimg.cc/nr3bNmbF/graphic-tee-2.png",
    ],
  },
  {
    id: 13,
    name: "Athletic Shorts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Grey", "Navy Blue"],
    price: 1799,
    description: "Breathable athletic shorts ideal for workouts.",
    material: "85% Polyester, 15% Spandex",
    stock: 85,
    images: [
      "https://i.postimg.cc/4yQG2Pkh/athletic-shorts-1.png",
      "https://i.postimg.cc/QCNxZkn8/athletic-shorts-2.png",
    ],
  },
  {
    id: 14,
    name: "Knitted Sweater",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Cream", "Taupe", "Maroon"],
    price: 3499,
    description: "Warm and cozy knitted sweater for cooler days.",
    material: "60% Wool, 40% Acrylic",
    stock: 55,
    images: [
      "https://i.postimg.cc/N00gX6F1/knitted-sweater-1.png",
      "https://i.postimg.cc/j6N8J4H5/knitted-sweater-2.png",
    ],
  },
  {
    id: 15,
    name: "Patterned Scarf",
    sizes: ["One Size"],
    colors: ["Blue Geometric", "Red Floral"],
    price: 999,
    description: "Stylish patterned scarf to complement any outfit.",
    material: "100% Polyester",
    stock: 120,
    images: [
      "https://i.postimg.cc/Wz7rYVX6/patterned-scarf-1.png",
      "https://i.postimg.cc/7ZXVVQ17/patterned-scarf-2.png",
    ],
  },
  // New items...
  {
    id: 16,
    name: "Harem Pants",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Khaki", "Navy Blue"],
    price: 2299,
    description: "Relaxed harem pants with an elastic waistband.",
    material: "100% Cotton",
    stock: 70,
    images: [
      "https://i.postimg.cc/YqLf8XZB/harem-pants-1.png",
      "https://i.postimg.cc/T2W9Xt5p/harem-pants-2.png",
    ],
  },
  {
    id: 17,
    name: "Trendy Sneakers",
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["White", "Black", "Red"],
    price: 3999,
    description: "Stylish sneakers with a cushioned sole for all-day comfort.",
    material: "Synthetic",
    stock: 90,
    images: [
      "https://i.postimg.cc/Jhtgt6XL/trendy-sneakers-1.png",
      "https://i.postimg.cc/YSmZT0Xs/trendy-sneakers-2.png",
    ],
  },
  {
    id: 18,
    name: "High-Waisted Skirt",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Grey", "Navy"],
    price: 2499,
    description: "Chic high-waisted skirt with a flattering fit.",
    material: "Polyester Blend",
    stock: 60,
    images: [
      "https://i.postimg.cc/zX9sMH0M/high-waisted-skirt-1.png",
      "https://i.postimg.cc/J3cHPRK1/high-waisted-skirt-2.png",
    ],
  },
  {
    id: 19,
    name: "Puffer Vest",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Grey", "Olive"],
    price: 3999,
    description: "Insulated puffer vest for added warmth during chilly days.",
    material: "100% Nylon",
    stock: 40,
    images: [
      "https://i.postimg.cc/Z5dm1h7R/puffer-vest-1.png",
      "https://i.postimg.cc/nV3kFgXy/puffer-vest-2.png",
    ],
  },
  {
    id: 20,
    name: "Cotton Sundress",
    sizes: ["S", "M", "L"],
    colors: ["Yellow", "Blue", "Green"],
    price: 3499,
    description: "Light and breezy cotton sundress perfect for summer.",
    material: "100% Cotton",
    stock: 50,
    images: [
      "https://i.postimg.cc/QMBKPdLR/cotton-sundress-1.png",
      "https://i.postimg.cc/TYP39JcX/cotton-sundress-2.png",
    ],
  },
  {
    id: 21,
    name: "Leather Boots",
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["Brown", "Black"],
    price: 6999,
    description: "Durable leather boots with a rugged design.",
    material: "Genuine Leather",
    stock: 30,
    images: [
      "https://i.postimg.cc/ncb4JfD9/leather-boots-1.png",
      "https://i.postimg.cc/yX8Z8h7G/leather-boots-2.png",
    ],
  },
  {
    id: 22,
    name: "Silk Blouse",
    sizes: ["S", "M", "L"],
    colors: ["Ivory", "Black", "Blush"],
    price: 4999,
    description: "Elegant silk blouse with a sophisticated sheen.",
    material: "100% Silk",
    stock: 45,
    images: [
      "https://i.postimg.cc/XJ0pYB4W/silk-blouse-1.png",
      "https://i.postimg.cc/L8x8J2Hb/silk-blouse-2.png",
    ],
  },
  {
    id: 23,
    name: "Wide-Leg Trousers",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Beige", "Black", "Navy"],
    price: 2999,
    description: "Flowy wide-leg trousers for a comfortable yet stylish look.",
    material: "Polyester Blend",
    stock: 80,
    images: [
      "https://i.postimg.cc/sXzLC2F1/wide-leg-trousers-1.png",
      "https://i.postimg.cc/nVznpX4m/wide-leg-trousers-2.png",
    ],
  },
  {
    id: 24,
    name: "Hooded Sweatshirt",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Grey", "Black", "Navy"],
    price: 2299,
    description: "Cozy hooded sweatshirt with a soft interior.",
    material: "80% Cotton, 20% Polyester",
    stock: 90,
    images: [
      "https://i.postimg.cc/Fz0B1m9S/hooded-sweatshirt-1.png",
      "https://i.postimg.cc/MHfHnHP8/hooded-sweatshirt-2.png",
    ],
  },
  {
    id: 25,
    name: "Wrap Dress",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Black", "Blue"],
    price: 2999,
    description: "Flattering wrap dress that cinches at the waist.",
    material: "95% Polyester, 5% Spandex",
    stock: 55,
    images: [
      "https://i.postimg.cc/W4Lq8J3m/wrap-dress-1.png",
      "https://i.postimg.cc/tR6DL6kJ/wrap-dress-2.png",
    ],
  },
  {
    id: 26,
    name: "Chino Pants",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Khaki", "Navy", "Charcoal"],
    price: 2399,
    description: "Versatile chino pants suitable for both casual and formal settings.",
    material: "98% Cotton, 2% Spandex",
    stock: 60,
    images: [
      "https://i.postimg.cc/76F1Dk1J/chino-pants-1.png",
      "https://i.postimg.cc/SsHh7ztS/chino-pants-2.png",
    ],
  },
  {
    id: 27,
    name: "Button-Up Cardigan",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gray", "Navy", "Maroon"],
    price: 2699,
    description: "Classic button-up cardigan with a relaxed fit.",
    material: "50% Wool, 50% Acrylic",
    stock: 75,
    images: [
      "https://i.postimg.cc/MpHXcG9w/button-up-cardigan-1.png",
      "https://i.postimg.cc/xTZp9b8H/button-up-cardigan-2.png",
    ],
  },
  {
    id: 28,
    name: "Fleece-Lined Leggings",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Gray", "Burgundy"],
    price: 1999,
    description: "Warm fleece-lined leggings perfect for colder weather.",
    material: "92% Polyester, 8% Spandex",
    stock: 80,
    images: [
      "https://i.postimg.cc/SRpF3W2L/fleece-lined-leggings-1.png",
      "https://i.postimg.cc/xdRRS5Z2/fleece-lined-leggings-2.png",
    ],
  },
  {
    id: 29,
    name: "Sleeveless Top",
    sizes: ["S", "M", "L"],
    colors: ["White", "Black", "Red"],
    price: 1399,
    description: "Lightweight sleeveless top for layering or wearing alone.",
    material: "100% Rayon",
    stock: 95,
    images: [
      "https://i.postimg.cc/Z5JvhHZh/sleeveless-top-1.png",
      "https://i.postimg.cc/4yv76D0r/sleeveless-top-2.png",
    ],
  },
  {
    id: 30,
    name: "Summer Romper",
    sizes: ["S", "M", "L"],
    colors: ["Coral", "Mint Green", "Navy"],
    price: 2799,
    description: "Fun and flirty summer romper with a cinched waist.",
    material: "100% Polyester",
    stock: 40,
    images: [
      "https://i.postimg.cc/8CPM3z3C/summer-romper-1.png",
      "https://i.postimg.cc/BPr71W9D/summer-romper-2.png",
    ],
  },
];

export default clothingItems;
