const clothingItems = [
  {
    id: 1,
    name: "Classic White T-Shirt",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black", "Grey"],
    price: 1999,
    description: "A classic white t-shirt made from 100% organic cotton.",
    material: "100% Cotton",
    stock: 120,
    images: [
      "https://i.postimg.cc/6QQh9366/white-front.png",
      "https://i.postimg.cc/CKLVSjfZ/Screenshot-2024-07-27-101056.png",
    ],
  },
  {
    id: 2,
    name: "Slim Fit Jeans",
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Blue", "Black", "Grey"],
    price: 4999,
    description: "Stylish slim fit jeans with a modern look.",
    material: "98% Cotton, 2% Elastane",
    stock: 75,
    images: [
      "https://i.postimg.cc/bJZrNX22/Screenshot-2024-07-27-101301.png",
      "https://i.postimg.cc/yYQGcwJN/Screenshot-2024-07-27-101413.png",
    ],
  },
  {
    id: 3,
    name: "Floral Summer Dress",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Blue", "Yellow"],
    price: 3999,
    description: "A beautiful floral summer dress perfect for sunny days.",
    material: "100% Polyester",
    stock: 50,
    images: [
      "https://i.postimg.cc/Dfsj8ShB/Screenshot-2024-07-27-101544.png",
      "https://i.postimg.cc/Dfsj8ShB/Screenshot-2024-07-27-101544.png",
    ],
  },
  {
    id: 4,
    name: "Men's Leather Jacket",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Brown"],
    price: 12.99,
    description: "Premium quality leather jacket for men.",
    material: "100% Genuine Leather",
    stock: 30,
    images: [
      "https://i.postimg.cc/fT1r81sT/Screenshot-2024-07-27-101740.png",
      "https://i.postimg.cc/KjMHb5ry/Screenshot-2024-07-27-101750.png",
    ],
  },
  {
    id: 5,
    name: "Comfy Hoodie",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Grey", "Black", "Navy Blue"],
    price: 2999,
    description: "A cozy and comfortable hoodie made from soft fabric.",
    material: "60% Cotton, 40% Polyester",
    stock: 100,
    images: [
      "https://i.postimg.cc/5ymb11mJ/Screenshot-2024-07-27-101936.png",
      "https://i.postimg.cc/g2840JZ3/Screenshot-2024-07-27-101955.png",
    ],
  },

  {
    id: 6,
    name: "Casual Chinos",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Beige", "Navy Blue", "Olive"],
    price: 3499,
    description: "Comfortable and stylish chinos for casual wear.",
    material: "100% Cotton",
    stock: 80,
    images: [
      "https://i.postimg.cc/zvpwhbkc/Screenshot-2024-07-27-102155.png",
      "https://i.postimg.cc/nh97FwN5/Screenshot-2024-07-27-102213.png",
    ],
  },
  {
    id: 7,
    name: "Striped Polo Shirt",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red/White", "Blue/White", "Green/White"],
    price: 2499,
    description: "A stylish striped polo shirt made from breathable fabric.",
    material: "100% Cotton",
    stock: 90,
    images: [
      "https://i.postimg.cc/6TJKdq5C/Screenshot-2024-07-27-102320.png",
      "https://i.postimg.cc/htKjwZcT/Screenshot-2024-07-27-102330.png",
    ],
  },
  {
    id: 8,
    name: "Women's Cardigan",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Grey", "Black", "Pink"],
    price: 4499,
    description: "A soft and warm cardigan for women.",
    material: "80% Wool, 20% Acrylic",
    stock: 40,
    images: [
      "https://i.postimg.cc/15C2hfZB/Screenshot-2024-07-27-102458.png",
      "https://i.postimg.cc/ydHrXRF1/Screenshot-2024-07-27-102505.png",
    ],
  },
  {
    id: 9,
    name: "Women's Kurti",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Pink", "Blue", "Green"],
    price: 2499,
    description: "A traditional Indian kurti with intricate embroidery.",
    material: "Cotton",
    stock: 60,
    images: ["url-front", "url-back"],
  },
  {
    id: 10,
    name: "Men's Sherwani",
    sizes: ["M", "L", "XL"],
    colors: ["Gold", "Maroon", "Beige"],
    price: 14999,
    description: "A classic men's sherwani with detailed designs.",
    material: "Silk",
    stock: 25,
    images: ["url-front", "url-back"],
  },
  {
    id: 11,
    name: "Women's Abaya",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Navy Blue", "Grey"],
    price: 7999,
    description: "A modest and elegant abaya for traditional wear.",
    material: "Chiffon",
    stock: 40,
    images: ["url-front", "url-back"],
  },
  {
    id: 12,
    name: "Men's Thobe",
    sizes: ["M", "L", "XL"],
    colors: ["White", "Grey", "Brown"],
    price: 4999,
    description: "A traditional thobe worn by men in Saudi Arabia.",
    material: "Cotton Blend",
    stock: 50,
    images: ["url-front", "url-back"],
  },
  {
    id: 13,
    name: "Women's Lehenga",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Green", "Purple"],
    price: 15999,
    description: "An exquisite lehenga for weddings and special occasions.",
    material: "Silk",
    stock: 20,
    images: ["url-front", "url-back"],
  },
  {
    id: 14,
    name: "Men's Kurta Pajama",
    sizes: ["M", "L", "XL"],
    colors: ["White", "Black", "Blue"],
    price: 3499,
    description: "A comfortable kurta pajama set for traditional wear.",
    material: "Cotton",
    stock: 75,
    images: ["url-front", "url-back"],
  },
  {
    id: 15,
    name: "Women's Salwar Kameez",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Yellow", "Pink", "Blue"],
    price: 3999,
    description: "A vibrant salwar kameez set with traditional prints.",
    material: "Cotton Blend",
    stock: 90,
    images: ["url-front", "url-back"],
  },
  {
    id: 16,
    name: "Men's Kandura",
    sizes: ["M", "L", "XL"],
    colors: ["White", "Beige", "Grey"],
    price: 4499,
    description: "A traditional kandura worn in the UAE and Gulf countries.",
    material: "Polyester Blend",
    stock: 45,
    images: ["url-front", "url-back"],
  },
  {
    id: 17,
    name: "Women's Anarkali Dress",
    sizes: ["S", "M", "L"],
    colors: ["Green", "Red", "Blue"],
    price: 6999,
    description: "An elegant anarkali dress for festive occasions.",
    material: "Silk Blend",
    stock: 35,
    images: ["url-front", "url-back"],
  },
  {
    id: 18,
    name: "Men's Pathani Suit",
    sizes: ["M", "L", "XL"],
    colors: ["Black", "White", "Grey"],
    price: 4999,
    description:
      "A traditional Pathani suit for men, popular in Pakistan and North India.",
    material: "Cotton",
    stock: 60,
    images: ["url-front", "url-back"],
  },
  {
    id: 19,
    name: "Women's Saree",
    sizes: ["One Size"],
    colors: ["Red", "Blue", "Gold"],
    price: 12999,
    description:
      "A beautiful saree with intricate embroidery, perfect for weddings.",
    material: "Silk",
    stock: 40,
    images: ["url-front", "url-back"],
  },
  {
    id: 20,
    name: "Men's Jubba",
    sizes: ["M", "L", "XL"],
    colors: ["White", "Grey", "Brown"],
    price: 5499,
    description: "A traditional Jubba worn in Islamic cultures.",
    material: "Cotton",
    stock: 55,
    images: ["url-front", "url-back"],
  },
  {
    id: 21,
    name: "Women's Pattu Pavadai",
    sizes: ["S", "M", "L"],
    colors: ["Pink", "Green", "Yellow"],
    price: 9999,
    description: "A traditional South Indian dress for young girls.",
    material: "Silk",
    stock: 30,
    images: ["url-front", "url-back"],
  },
  {
    id: 22,
    name: "Men's Achkan",
    sizes: ["M", "L", "XL"],
    colors: ["Gold", "Maroon", "Beige"],
    price: 15999,
    description: "A regal achkan for men, worn on special occasions.",
    material: "Silk",
    stock: 25,
    images: ["url-front", "url-back"],
  },
  {
    id: 23,
    name: "Women's Kaftan",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Purple", "Blue", "Green"],
    price: 5499,
    description: "A flowing kaftan perfect for casual and traditional wear.",
    material: "Chiffon",
    stock: 50,
    images: ["url-front", "url-back"],
  },
  {
    id: 24,
    name: "Men's Churidar Kurta",
    sizes: ["M", "L", "XL"],
    colors: ["White", "Black", "Navy"],
    price: 5999,
    description: "A stylish churidar kurta set for traditional events.",
    material: "Cotton",
    stock: 70,
    images: ["url-front", "url-back"],
  },
  {
    id: 25,
    name: "Women's Sharara",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Green", "Pink"],
    price: 8999,
    description: "A gorgeous sharara set with intricate embellishments.",
    material: "Georgette",
    stock: 45,
    images: ["url-front", "url-back"],
  },
  {
    id: 26,
    name: "Men's Angrakha",
    sizes: ["M", "L", "XL"],
    colors: ["Brown", "Beige", "Gold"],
    price: 6999,
    description: "A traditional angrakha worn by men in Rajasthan.",
    material: "Cotton Silk",
    stock: 30,
    images: ["url-front", "url-back"],
  },
  {
    id: 27,
    name: "Women's Gharara",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Pink", "Yellow", "Blue"],
    price: 8499,
    description: "A stylish gharara with intricate lacework.",
    material: "Silk",
    stock: 40,
    images: ["url-front", "url-back"],
  },
  {
    id: 28,
    name: "Men's Dhoti Kurta",
    sizes: ["M", "L", "XL"],
    colors: ["White", "Yellow", "Green"],
    price: 3999,
    description: "A traditional dhoti kurta set for festive occasions.",
    material: "Cotton",
    stock: 60,
    images: ["url-front", "url-back"],
  },
  {
    id: 29,
    name: "Women's Patiala Suit",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Blue", "Green"],
    price: 4799,
    description: "A vibrant Patiala suit with a comfortable fit.",
    material: "Cotton Blend",
    stock: 80,
    images: ["url-front", "url-back"],
  },
  {
    id: 30,
    name: "Men's Lungi",
    sizes: ["One Size"],
    colors: ["White", "Blue", "Green"],
    price: 999,
    description: "A traditional lungi worn in South India.",
    material: "Cotton",
    stock: 100,
    images: ["url-front", "url-back"],
  },

  {
    id: 31,
    name: "Elegant Kurti Set",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Purple", "Beige"],
    price: 2999,
    description: "Elegant kurti set with matching dupatta.",
    material: "Georgette",
    stock: 70,
    images: ["url-front", "url-back"],
  },
  {
    id: 32,
    name: "Formal Maxi Dress",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Dark Green", "Navy"],
    price: 3699,
    description: "Formal maxi dress suitable for events.",
    material: "Polyester Blend",
    stock: 55,
    images: ["url-front", "url-back"],
  },
  {
    id: 33,
    name: "Indian Tunic",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Yellow", "Pink"],
    price: 2299,
    description: "Traditional tunic with embroidery.",
    material: "Cotton",
    stock: 80,
    images: ["url-front", "url-back"],
  },
  {
    id: 34,
    name: "Western Shift Dress",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Grey", "Maroon", "Blue"],
    price: 3299,
    description: "Simple and elegant western shift dress.",
    material: "Polyester",
    stock: 65,
    images: ["url-front", "url-back"],
  },
  {
    id: 35,
    name: "Indian Anarkali Suit",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Gold", "Emerald"],
    price: 4999,
    description: "Flowy anarkali suit with intricate designs.",
    material: "Chiffon",
    stock: 45,
    images: ["url-front", "url-back"],
  },
  {
    id: 36,
    name: "Elegant Western Jumpsuit",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Grey", "Blue"],
    price: 3999,
    description: "Sophisticated jumpsuit for formal occasions.",
    material: "Polyester Blend",
    stock: 50,
    images: ["url-front", "url-back"],
  },
  {
    id: 37,
    name: "Traditional Salwar Kameez",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Green", "Red", "Blue"],
    price: 3499,
    description: "Classic salwar kameez for traditional wear.",
    material: "Cotton",
    stock: 75,
    images: ["url-front", "url-back"],
  },
  {
    id: 38,
    name: "Formal Western Blouse",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black", "Blue"],
    price: 2199,
    description: "Elegant formal blouse for western outfits.",
    material: "Silk Blend",
    stock: 90,
    images: ["url-front", "url-back"],
  },
  {
    id: 39,
    name: "Classic Saree",
    sizes: ["Free Size"],
    colors: ["Red", "Blue", "Green"],
    price: 6999,
    description: "Timeless saree with classic design.",
    material: "Silk",
    stock: 35,
    images: ["url-front", "url-back"],
  },
  {
    id: 40,
    name: "Elegant Western Skirt",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Beige", "Navy"],
    price: 2499,
    description: "Chic western skirt suitable for various occasions.",
    material: "Polyester Blend",
    stock: 80,
    images: ["url-front", "url-back"],
  },
  {
    id: 41,
    name: "Traditional Lehenga Choli",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Purple", "Gold", "Red"],
    price: 12999,
    description: "Richly adorned lehenga choli with intricate embroidery.",
    material: "Silk",
    stock: 30,
    images: ["url-front", "url-back"],
  },
  {
    id: 42,
    name: "Formal Western Dress Pants",
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Charcoal", "Black", "Navy"],
    price: 2799,
    description: "Tailored western dress pants for formal settings.",
    material: "Wool Blend",
    stock: 60,
    images: ["url-front", "url-back"],
  },
  {
    id: 43,
    name: "Elegant Churidar",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Maroon", "Cream", "Green"],
    price: 3499,
    description: "Elegant churidar with traditional detailing.",
    material: "Cotton Blend",
    stock: 55,
    images: ["url-front", "url-back"],
  },
  {
    id: 44,
    name: "Western Shift Dress",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Red", "Gray"],
    price: 3299,
    description: "Sophisticated shift dress for a polished look.",
    material: "Polyester",
    stock: 65,
    images: ["url-front", "url-back"],
  },
  {
    id: 45,
    name: "Traditional Anarkali Dress",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Turquoise", "Purple", "Pink"],
    price: 3999,
    description: "Flowy anarkali dress with beautiful prints.",
    material: "Georgette",
    stock: 40,
    images: ["url-front", "url-back"],
  },
  {
    id: 46,
    name: "Formal Western Blazer",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Gray", "Navy"],
    price: 3999,
    description: "Tailored blazer for formal western wear.",
    material: "Wool Blend",
    stock: 55,
    images: ["url-front", "url-back"],
  },
  {
    id: 47,
    name: "Classic Salwar Suit",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Beige", "Pink", "Purple"],
    price: 2999,
    description: "Classic salwar suit with simple yet elegant design.",
    material: "Cotton",
    stock: 70,
    images: ["url-front", "url-back"],
  },
  {
    id: 48,
    name: "Formal Western Maxi Skirt",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Gray", "Navy"],
    price: 2999,
    description: "Elegant maxi skirt suitable for formal occasions.",
    material: "Polyester",
    stock: 60,
    images: ["url-front", "url-back"],
  },
  {
    id: 49,
    name: "Indian Kurta Set",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Yellow", "Green"],
    price: 3299,
    description: "Traditional kurta set with matching pants.",
    material: "Cotton Blend",
    stock: 50,
    images: ["url-front", "url-back"],
  },
  {
    id: 50,
    name: "Chic Western Jumpsuit",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Blue", "Maroon"],
    price: 3999,
    description: "Stylish jumpsuit for a chic look.",
    material: "Polyester Blend",
    stock: 45,
    images: ["url-front", "url-back"],
  },
  {
    id: 51,
    name: "Indian Patiala Suit",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Green", "Purple", "Pink"],
    price: 3499,
    description: "Traditional patiala suit with intricate embroidery.",
    material: "Cotton",
    stock: 60,
    images: ["url-front", "url-back"],
  },
  {
    id: 52,
    name: "Western A-Line Dress",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Red", "Gray"],
    price: 3299,
    description: "Elegant A-line dress for western outfits.",
    material: "Polyester Blend",
    stock: 55,
    images: ["url-front", "url-back"],
  },
  {
    id: 53,
    name: "Indian Sherwani",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gold", "Red", "Maroon"],
    price: 7999,
    description: "Traditional sherwani with beautiful embroidery.",
    material: "Silk",
    stock: 30,
    images: ["url-front", "url-back"],
  },
  {
    id: 54,
    name: "Western Cape Dress",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Beige", "Maroon"],
    price: 3499,
    description: "Stylish cape dress for a trendy look.",
    material: "Polyester",
    stock: 40,
    images: ["url-front", "url-back"],
  },
  {
    id: 55,
    name: "Elegant Anarkali Kurta",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Turquoise", "Pink", "Purple"],
    price: 3999,
    description: "Graceful anarkali kurta with traditional flair.",
    material: "Georgette",
    stock: 50,
    images: ["url-front", "url-back"],
  },
  {
    id: 56,
    name: "Formal Western Dress Shirt",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Blue", "Black"],
    price: 2499,
    description: "Elegant dress shirt for formal western wear.",
    material: "Cotton Blend",
    stock: 70,
    images: ["url-front", "url-back"],
  },
  {
    id: 57,
    name: "Indian Kurtas",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Green", "White"],
    price: 2799,
    description: "Traditional kurtas with simple yet elegant designs.",
    material: "Cotton",
    stock: 80,
    images: ["url-front", "url-back"],
  },
  {
    id: 58,
    name: "Chic Western Blazer",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gray", "Black", "Navy"],
    price: 3999,
    description: "Stylish western blazer for formal and casual wear.",
    material: "Wool Blend",
    stock: 45,
    images: ["url-front", "url-back"],
  },
  {
    id: 59,
    name: "Elegant Indian Gown",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gold", "Silver", "Purple"],
    price: 4999,
    description: "Elegant gown with intricate Indian embroidery.",
    material: "Silk",
    stock: 35,
    images: ["url-front", "url-back"],
  },
  {
    id: 60,
    name: "Formal Western Tunic",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Beige", "Blue"],
    price: 2899,
    description: "Chic western tunic for a sophisticated look.",
    material: "Polyester",
    stock: 65,
    images: ["url-front", "url-back"],
  },
];

export default clothingItems;
