const sizeCharts = {
  women: {
    womenTop: [
      {
        size: "XS",
        bust: "32.0",
        frontlength: "24.0",
        sleevelength: "23.0",
        waist: "25.0",
      },
      {
        size: "S",
        bust: "34.0",
        frontlength: "24.5",
        sleevelength: "23.5",
        waist: "27.0",
      },
      {
        size: "M",
        bust: "36.0",
        frontlength: "25.0",
        sleevelength: "24.0",
        waist: "29.0",
      },
      {
        size: "L",
        bust: "38.0",
        frontlength: "25.5",
        sleevelength: "24.5",
        waist: "31.0",
      },
      {
        size: "XL",
        bust: "40.0",
        frontlength: "26.0",
        sleevelength: "25.0",
        waist: "33.0",
      },
      {
        size: "XXL",
        bust: "42.0",
        frontlength: "26.5",
        sleevelength: "25.5",
        waist: "35.0",
      },
    ],
    WomenBottom: [
      {
        size: "26",
        brandsize: "XS",
        waist: "26.0",
        inseamlength: "28.5",
        outseamlength: "38.0",
        hips: "36.0",
      },
      {
        size: "28",
        brandsize: "S",
        waist: "28.0",
        inseamlength: "29.0",
        outseamlength: "39.0",
        hips: "38.0",
      },
      {
        size: "30",
        brandsize: "M",
        waist: "30.0",
        inseamlength: "29.5",
        outseamlength: "40.0",
        hips: "40.0",
      },
      {
        size: "32",
        brandsize: "L",
        waist: "32.0",
        inseamlength: "30.0",
        outseamlength: "41.0",
        hips: "42.0",
      },
      {
        size: "34",
        brandsize: "XL",
        waist: "34.0",
        inseamlength: "30.5",
        outseamlength: "42.0",
        hips: "44.0",
      },
      {
        size: "36",
        brandsize: "XXL",
        waist: "36.0",
        inseamlength: "31.0",
        outseamlength: "43.0",
        hips: "46.0",
      },
    ],
  },
  men: {
    mensUpperWear: [
      {
        size: "39",
        chest: "41.0",
        frontlength: "29.0",
        acrossshoulder: "18.0",
      },
      {
        size: "40",
        chest: "42.0",
        frontlength: "29.5",
        acrossshoulder: "18.5",
      },
      {
        size: "42",
        chest: "44.0",
        frontlength: "30.0",
        acrossshoulder: "19.0",
      },
      {
        size: "44",
        chest: "46.0",
        frontlength: "30.5",
        acrossshoulder: "19.5",
      },
    ],
    mensBottom: [
      {
        size: "28",
        waist: "28.0",
        inseamlength: "30.0",
        outseamlength: "40.0",
        hips: "34.0",
      },
      {
        size: "30",
        waist: "30.0",
        inseamlength: "30.5",
        outseamlength: "41.0",
        hips: "36.0",
      },
      {
        size: "32",
        waist: "32.0",
        inseamlength: "31.0",
        outseamlength: "42.0",
        hips: "38.0",
      },
      {
        size: "34",
        waist: "34.0",
        inseamlength: "31.5",
        outseamlength: "42.5",
        hips: "40.0",
      },
      {
        size: "36",
        waist: "36.0",
        inseamlength: "32.0",
        outseamlength: "43.0",
        hips: "42.0",
      },
    ],
  },

  boys: {
    boysUpperWear: [
      {
        size: "8-9Y",
        chest: "27.0",
        frontlength: "22.0",
        acrossshoulder: "12.9",
      },
      {
        size: "9-10Y",
        chest: "28.5",
        frontlength: "23.0",
        acrossshoulder: "13.3",
      },
      {
        size: "11-12Y",
        chest: "30.0",
        frontlength: "24.0",
        acrossshoulder: "13.6",
      },
      {
        size: "13-14Y",
        chest: "32.0",
        frontlength: "25.0",
        acrossshoulder: "14.1",
      },
    ],
    boysBottom: [
      {
        size: "4-5Y",
        waist: "22.8",
        inseamlength: "14.0",
        outseamlength: "19.0",
      },
      {
        size: "5-6Y",
        waist: "23.6",
        inseamlength: "15.5",
        outseamlength: "20.5",
      },
      {
        size: "7-8Y",
        waist: "24.8",
        inseamlength: "17.0",
        outseamlength: "22.0",
      },
    ],
  },
  girls: {
    girlsTop: [
      {
        size: "4-5Y",
        chest: "24.0",
        frontlength: "15.0",
        waist: "22.0",
        acrossshoulder: "9.5",
      },
      {
        size: "6-7Y",
        chest: "26.0",
        frontlength: "16.0",
        waist: "24.0",
        acrossshoulder: "10.3",
      },
      {
        size: "7-8Y",
        chest: "28.0",
        frontlength: "17.0",
        waist: "26.0",
        acrossshoulder: "11.0",
      },
      {
        size: "9-10Y",
        chest: "30.0",
        frontlength: "18.0",
        waist: "28.0",
        acrossshoulder: "11.8",
      },
    ],
    girlsBottom: [
      {
        size: "4-5Y",
        waist: "18.0",
        inseamlength: "16.0",
        outseamlength: "24.0",
      },
      {
        size: "5-6Y",
        waist: "19.0",
        inseamlength: "17.0",
        outseamlength: "25.0",
      },
      {
        size: "6-7Y",
        waist: "20.0",
        inseamlength: "18.0",
        outseamlength: "26.0",
      },
    ],
  },
};

export default sizeCharts;
